export const GLOSSARY = {
  "isotope": "Atoms of the same element with the same number of protons but different numbers of neutrons.",
  "MeV": "Mega-electronvolt, a unit of energy used in particle physics.",
  "atomic mass unit": "A standard unit of mass that quantifies mass on an atomic or molecular scale.",
  "Cherenkov": "Cherenkov radiation is the blue glow produced when particles travel faster than light in water.",
  "PUREX": "Plutonium Uranium Reduction Extraction, the standard method for reprocessing spent nuclear fuel.",
  "baseload": "The minimum level of electricity demand supplied continuously to the grid over a period of time.",
  "MOX": "Mixed Oxide fuel, a blend of plutonium and uranium used to recycle spent fuel.",
  "chain reaction": "A self-sustaining series of nuclear fissions triggered by neutrons.",
  "fission": "The splitting of a heavy atomic nucleus into lighter fragments, releasing energy.",
  "protons": "Positively charged subatomic particles found in the nucleus.",
  "neutrons": "Neutral subatomic particles found in the nucleus along with protons.",
  "Uranium-235": "A fissile isotope of uranium that easily sustains a nuclear chain reaction.",
  "Uranium-238": "The most common isotope of uranium, which is not easily fissile.",
  "control rods": "Rods made of neutron-absorbing material used to control the rate of fission.",
  "moderator": "A medium (like water) that slows down fast neutrons, increasing the chance of fission.",
  "alpha particle": "Heavily ionizing radiation consisting of two protons and two neutrons.",
  "beta particle": "A high-energy, high-speed electron or positron emitted by radioactive decay.",
  "gamma rays": "High-frequency electromagnetic radiation emitted from the atomic nucleus.",
  "half-life": "The time required for half the atomic nuclei of a radioactive sample to decay.",
  "PWR": "Pressurised Water Reactor, a common type of reactor where water is kept under high pressure.",
  "BWR": "Boiling Water Reactor, a reactor type where water boils directly in the core to create steam.",
  "SMR": "Small Modular Reactor, a newer class of smaller, factory-built reactors.",
  "spent fuel": "Nuclear fuel that has been irradiated in a reactor and is no longer efficient for power generation.",
  "decay": "The process by which an unstable atomic nucleus loses energy by emitting radiation."
};